### PR TITLE
fixes responsiveness issues #42 #44

### PR DESCRIPTION
**Pull request by ShobhitPatra**
fixes issues #42 and #44

### CODE REVIEW

**Comment by mohitahlawat2001** [comment]
provide photo after correcting bug

**Comment by ShobhitPatra** [comment]
@mohitahlawat2001  I need some demo env-variables at /client.
Currently it is showing a bunch of errors .

Also, our read.me does not hold instructions for starting the local development server. It is being difficult for me.

Please share other details which i need while setting up the project perfectly.

**Comment by ShobhitPatra** [comment]
Having said that , I copied just the required jsx files to a separate project to solve the issues as the issues were a merely of styling problems. 
Screenshot from 2024-10-06 10-15-27
Screenshot from 2024-10-06 10-20-48

**Comment by mohitahlawat2001** [comment]
i added .env.example for reference .env

**Comment by mohitahlawat2001** [comment]
resolve conflict

**Comment by mohitahlawat2001** [comment]
no response

**Pull request closed without merging**
