### PR TITLE
Features

### PR DESCRIPTION
**Pull request by shiv-sk**
hey bro i have finished my work and submitting to the merge request please process as soon as possible if any error please inform it to me below are the screen shots of my work i am not a frontend person but i tried from ur previous code and once again thank u for giving me opportunity to participate in the project ...

i am worked in making restaurant model , foodmenu model and controllers and storing in database and fetching from database showing it on the frontend side 
installed external package:
cloudinary for handling files 
axios for handling api calls

env variables to set in env file
CLOUD_NAME=
CLOUD_API_KEY=
CLOUD_API_SECRET=

cloudinary is a free cloud storage i have used in this project for handling file (images) 

in env.example file i have mentioned used env variables 
 
Screenshot 2024-10-24 124205
Screenshot 2024-10-24 124132
Screenshot 2024-10-24 124114
Screenshot 2024-10-24 124029

### CODE REVIEW

**Comment by shiv-sk** [comment]
@mohitahlawat2001 hey bro is there any issue for accepting my pr

**Review by mohitahlawat2001 — COMMENTED** [review]
not able continue with this feature, as there is not data i am able to see

**Comment by shiv-sk** [comment]
Hey bro can u explain me with detail so that I can correct my mistakes

**Comment by mohitahlawat2001** [comment]
we can get data from link which i used in project, as i can see do not using that link to get data,

**Comment by shiv-sk** [comment]
hey bro can explain me what i need to do correct my mistakes  means what are your thoughts on this project and what kind of project you want to make or i just need to handle only authentication and authorization

**Comment by shiv-sk** [comment]
> we can get data from link which i used in project, as i can see do not using that link to get data,

Ok bro I will only maintain the authentication and authorisation process I will just response from database

**Comment by mohitahlawat2001** [comment]
> > we can get data from link which i used in project, as i can see do not using that link to get data,
> 
> Ok bro I will only maintain the authentication and authorisation process I will adjust response from database

sure make sure you use mongo db

**Comment by shiv-sk** [comment]
@mohitahlawat2001 hey bro as u mentioned i have made the changes kindly provide the cloudinary credentials in env file and mongodb cluster url

**Comment by mohitahlawat2001** [comment]
you are over engg things which are not needed

**Pull request closed without merging**
