### PR TITLE
Added Backend for storing user data , orders and for authentication

### PR DESCRIPTION
**Pull request by kumartushar0605**

### CODE REVIEW

**Comment by mohitahlawat2001** [comment]
Can you show how it's working using video , also showing in postman, it will be helpful

**Comment by kumartushar0605** [comment]
@mohitahlawat2001 I have made a video that shows how it stores user data and orders so , please check this video

https://github.com/user-attachments/assets/0264e1b5-2302-4b8b-bc8d-38f1673c8407

**Review by mohitahlawat2001 — CHANGES_REQUESTED** [review]
about me page not working , check it  please

**Comment by kumartushar0605** [comment]
@mohitahlawat2001  i have fixed the about page now it's perfectly working , please merge it 

Screenshot (171)

**Comment by mohitahlawat2001** [comment]
Did you  make .env.example file
Place variable for db

**Comment by kumartushar0605** [comment]
@mohitahlawat2001 bro i have added the env file now for db , now please merge it , it's a request every thing is working fine

**Comment by mohitahlawat2001** [comment]
Conflicting files
src/components/Header.js
src/components/Login.js
need to change these file , resolve conflict

**Comment by kumartushar0605** [comment]
@mohitahlawat2001  brother I fixed the issue now please merge it , I have worked very hard on this so please brother merge it

**Comment by mohitahlawat2001** [comment]
show error please correct these error

**Comment by kumartushar0605** [comment]
@mohitahlawat2001 brother now i have checked every single line of code and fixed everything , now please merge it

**Comment by kumartushar0605** [comment]
@mohitahlawat2001 bro please merge it

**Comment by mohitahlawat2001** [comment]
nothing is showing after deploy , 
did you try run in your system

**Comment by mohitahlawat2001** [comment]
still same
image

**Comment by kumartushar0605** [comment]
@mohitahlawat2001  bro now can you check again in your system is it working or not 
In my its working fine 
Screenshot (173)
Screenshot (174)

**Comment by kumartushar0605** [comment]
@mohitahlawat2001 thanks brother

**Pull request merged**
